// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStore.Products.Infrastructure.Foundation;

namespace MusicStore.Products.Api.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20190520161547_ChangeProductHistoryQuantityType")]
    partial class ChangeProductHistoryQuantityType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicStore.Products.Core.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProductId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("ImagePath");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MusicStore.Products.Core.Products.ProductHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProductHistoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<DateTime>("OccuredOnUtc");

                    b.Property<decimal>("PricePerItem");

                    b.Property<string>("ProductName");

                    b.Property<int>("Qunatity");

                    b.Property<string>("TransactionId");

                    b.HasKey("Id");

                    b.HasIndex("Email", "TransactionId");

                    b.ToTable("ProductHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
